name: Terraform Plan

on: [push, pull_request]

jobs:
    terraform-plan:
      runs-on: ubuntu-latest
      name: terraform-plan
      steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - id: init
        working-directory: terraform
        run: terraform init

      - id: validate
        working-directory: terraform
        run: terraform validate

      - id: generate-private-key
        working-directory: terraform
        run: openssl genrsa -out oci_api_key.pem 2048

      - id: generate-public-key
        working-directory: terraform
        run: openssl rsa -pubout -in oci_api_key.pem -out oci_api_key_public.pem
